Exclude globalized attrs on role merge
hitobito/hitobito_die_mitte pull request #197
Opened 2022-06-22 07:37 UTC by TheWalkingLeek

Merge first: https://github.com/hitobito/hitobito/pull/1768

2022-07-05 10:06 UTC, carlobeltrame commented on app/models/die_mitte/role.rb
> +    self.merge_excluded_attributes = globalize_attribute_names
Macht das wirklich was wir wollen? `globalize_attribute_names` sind ja die tatsächlichen Datenbankspalten `label_de`, `label_fr` etc.. Wenn wir die ausschliessen, wie verhält es sich dann beim Mergen wenn ein Label in mehreren Sprachen vorhanden ist? Der von globalize generierte Setter `label=` schaut ja auf die aktuelle Sprache, würde das dann nicht die restlichen Sprachen ignorieren während dem Merge?

2022-07-05 10:08 UTC, carlobeltrame commented on app/models/die_mitte/role.rb
> +    self.merge_excluded_attributes = globalize_attribute_names
Für so einen Fall wäre dann wohl ein Test noch spannend, egal für welches Verhalten wir uns entscheiden.

2022-07-05 21:37 UTC, kronn requested changes
Eine Spec als Doku für das im Wagon geänderte Verhalten fehlt mir auch noch.

2022-08-02 07:36 UTC, TheWalkingLeek commented
Also in erster Linie:
Die übersetzten Labels sind ein Mitte spezifisches Feature, daher tritt es nur hier auf.
Das Problem ist, dass diese Übersetzungen in einer anderen Tabelle festgehalten werden. Und da sie im `used_attributes` sind, versucht der Merger die Spalten in der `roles` Tabelle zu finden.
Daher wird aktuell nur das aktuelle Label gemerged. Ziel wäre es aber wohl dass alle zusammengeführt werden, mache dazu noch ein Issue. Der nun erstellte Spec muss dann natürlich angepasst werden :)

2022-08-02 07:42 UTC, TheWalkingLeek commented
Besagtes Issue: https://github.com/hitobito/hitobito_die_mitte/issues/201

2022-08-02 09:20 UTC, kronn approved these changes

2022-08-02 09:20 UTC, merged